### ISSUE TITLE
Feature request - specify spotify playlist

### ISSUE THREAD

**Issue by rlayne** [mbharanya/Spotify-To-Beatsaber#2]
I have a few playlists I'd like to run the tool on - and way too many songs unrelated to beat saber on my entire spotify account.  It'd be good to selectively run your tool on a specific playlist if possible (I haven't looked at spotify's API, should be though, right?)

**Comment by mbharanya** [comment]
Hey @rlayne,
I know it's been a while but I decided to implement the feature so that you can specify the playlist with the `--mode=playlist` and `playlist-name=<myplaylistname>` features.
I hope you / other people are still interested :)
